# Shell variables
# Generated by 'wal'
wallpaper='/home/diseo/.wallpapers/flowers.png'

# Special
background='#0a1116'
foreground='#e4dcd2'
cursor='#e4dcd2'

# Colors
color0='#0a1116'
color1='#906F65'
color2='#7B8479'
color3='#8C877A'
color4='#D38B77'
color5='#7C8A82'
color6='#A39F90'
color7='#e4dcd2'
color8='#9f9a93'
color9='#906F65'
color10='#7B8479'
color11='#8C877A'
color12='#D38B77'
color13='#7C8A82'
color14='#A39F90'
color15='#e4dcd2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
